import React from 'react';

const AIOT = () => {
  return (
    <div className="pt-2 pb-2 min-h-screen bg-slate-50 font-sans">
      <div className="mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header Hero Section */}
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8 md:p-14 mb-1 transition-all hover:shadow-md">
          <div className="flex flex-wrap items-center gap-3 text-xs md:text-sm font-bold text-blue-600 uppercase tracking-widest mb-6">
            <span>IoTrenetics</span>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-600"></span>
            <span>Intelligence in Motion</span>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-600"></span>
            <span>Industry Insight Paper</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 leading-tight mb-6 tracking-tight">
            AIOT
          </h1>
          <p className="text-xl md:text-2xl text-slate-600 font-light leading-relaxed">
            AI + IoT: Building Intelligent Environments with Data-Driven Decision Making & Secure Connected Systems
          </p>
        </div>

        {/* Article Body */}
        <article className="bg-white rounded-3xl shadow-sm border border-slate-200 p-8 md:p-14">
          <section className="mb-12">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6 tracking-tight border-b pb-4">Connected but Not Intelligent: The Gap That AIoT Closes</h2>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              Homes, offices, and industrial facilities are generating more data than ever before. Sensors measure temperature, occupancy, energy draw, machine vibration, access events, and dozens of other parameters — continuously, across millions of devices worldwide. Yet the majority of this data is never used. It is collected, stored, and discarded — a vast operational resource that delivers no return.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              The problem is not connectivity. Modern buildings and facilities are increasingly connected. The problem is intelligence. Most IoT deployments remain rule-based: if temperature exceeds a threshold, trigger an alert. If a door is opened after hours, send a notification. These systems respond to conditions they were explicitly programmed for and nothing else. They do not learn. They do not adapt. They cannot anticipate.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed">
              AIoT — the deliberate integration of Artificial Intelligence with the Internet of Things — changes this fundamentally. It transforms connected systems from passive data collectors into active, reasoning environments: spaces that analyse patterns, make predictions, optimise behaviour autonomously, and respond to conditions their designers never anticipated. The shift is not incremental. It is architectural.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-8 tracking-tight border-b pb-4">Why Connected Systems Fall Short Without Intelligence</h2>
            
            <h3 className="text-xl font-bold text-slate-800 mb-4 text-blue-600">Residential Environments</h3>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              The consumer smart home market has grown rapidly, but the reality for most households is a collection of disconnected devices managed through separate applications, responding to manually configured rules, and generating data that goes entirely unanalysed. The intelligence is shallow, the integration is fragmented, and the experience frequently fails to justify the investment.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-4">
              More significantly, the security posture of most residential IoT deployments is poor. Consumer devices are routinely shipped with default credentials, infrequent firmware updates, and no network segmentation — creating vulnerabilities that sophisticated attackers actively exploit. A connected home without a coherent security architecture is not a safer home. It is a more exposed one.
            </p>
            <ul className="list-disc pl-6 space-y-3 text-lg text-slate-700 mb-10">
              <li>Devices operate in silos with no shared context or cross-system learning</li>
              <li>Automation is static and rule-based, incapable of adapting to changing patterns or preferences</li>
              <li>Security vulnerabilities in consumer IoT devices create household-level cyber exposure</li>
              <li>Data generated by devices is collected but never analysed for behavioural insights or optimisation</li>
              <li>Manual configuration and management burden undermines the value proposition of automation</li>
            </ul>

            <h3 className="text-xl font-bold text-slate-800 mb-4 text-blue-600">Commercial and Industrial Environments</h3>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              At enterprise and industrial scale, the gap between connectivity and intelligence carries material financial consequences. Large facilities generate sensor data volumes that far exceed human capacity to monitor and interpret. The result is alert fatigue, missed signals, and decisions made on intuition rather than evidence — despite the existence of the data that would support better choices.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-4">
              Static, threshold-based systems also respond after the fact. By the time an alert is triggered, the operational window to prevent failure or waste has typically already closed. Without predictive capability — without the ability to detect that conditions are trending toward a problem before the threshold is breached — reactive response is the only option available.
            </p>
            <ul className="list-disc pl-6 space-y-3 text-lg text-slate-700 mb-6">
              <li>Data overload without analytical capacity produces noise rather than operational intelligence</li>
              <li>Absence of predictive decision-making forces reliance on reactive, high-cost interventions</li>
              <li>Large-scale IoT deployments create complex attack surfaces with significant security implications</li>
              <li>Static operational systems fail to optimise resource utilisation as conditions change</li>
              <li>Operational decisions are delayed by the absence of real-time, synthesised insight</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-8 tracking-tight border-b pb-4">What AIoT Enables: Applications Across Environments</h2>

            <div className="bg-slate-50 rounded-2xl p-6 mb-8 border border-slate-100">
              <h3 className="text-xl font-bold text-slate-800 mb-6">Residential Applications</h3>
              
              <h4 className="font-semibold text-slate-900 text-lg mb-2">Adaptive Home Intelligence</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                Where rule-based automation asks 'what did the user configure?', AIoT asks 'what does this household actually need right now?' Machine learning models trained on occupancy patterns, usage history, and environmental data build a continuously updated model of how a home is used — and optimise lighting, climate, energy draw, and device behaviour accordingly, without requiring manual reconfiguration as habits change.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Intelligent Energy Management</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                AIoT systems move beyond scheduled control of heating and cooling to dynamic energy optimisation: forecasting occupancy, monitoring real-time tariff pricing, modelling thermal behaviour of the building envelope, and adjusting consumption to minimise cost while maintaining comfort. Over time, the system learns the thermal characteristics of the specific property and the specific household — producing personalised efficiency outcomes that generic systems cannot replicate.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Context-Aware Security</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                AI-enhanced security systems do not simply detect motion — they contextualise it. Computer vision and behavioural analytics distinguish between a family member returning home, a delivery driver, and an unfamiliar individual behaving atypically. False alarm rates fall sharply. Genuine anomalies are escalated with greater precision. The system learns what normal looks like in a specific environment and becomes increasingly accurate at identifying what does not fit.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Personalised Living Environments</h4>
              <p className="text-slate-700 leading-relaxed mb-2">
                AIoT platforms can learn individual preferences for lighting, temperature, and device behaviour at a granular level — adjusting automatically as people move through a home, as time of day changes, and as seasonal patterns shift. The environment becomes genuinely responsive: not to pre-programmed instructions, but to inferred preferences derived from observed behaviour.
              </p>
            </div>

            <div className="bg-slate-50 rounded-2xl p-6 border border-slate-100">
              <h3 className="text-xl font-bold text-slate-800 mb-6">Commercial and Industrial Applications</h3>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Data-Driven Operational Decision Making</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                AIoT platforms consolidate sensor data from across facilities, process it through analytical models, and surface actionable intelligence to operational teams — not raw data, but interpreted signals. The distinction matters enormously at scale: a facility manager presented with 50,000 sensor readings per hour has no useful information. The same manager presented with three prioritised alerts and a predicted equipment failure within 72 hours has something they can act on.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Intelligent Facility and Building Management</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                AI models applied to building management system data enable a level of operational optimisation that manual management and simple automation cannot approach. Occupancy prediction, load forecasting, fault detection, and preventive maintenance scheduling are handled autonomously — with the system continuously learning from operational outcomes to improve accuracy over time. The facility does not just respond to conditions; it anticipates them.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Predictive Business and Operational Intelligence</h4>
              <p className="text-slate-700 leading-relaxed mb-6">
                In commercial and industrial settings, the aggregate intelligence of an AIoT system extends beyond individual asset management to business-level insight: production yield forecasting, supply chain signal integration, demand-responsive scheduling, and energy cost optimisation at the enterprise level. Connected operational data becomes a strategic asset, informing decisions that would otherwise be made on incomplete information.
              </p>

              <h4 className="font-semibold text-slate-900 text-lg mb-2">Autonomous Operations and Process Control</h4>
              <p className="text-slate-700 leading-relaxed mb-2">
                At the furthest end of the AIoT maturity curve, AI models take direct control of operational parameters — adjusting process variables in real time, routing workflows dynamically, and managing system states without human intervention except at the exception level. Human operators shift from managing routine operations to supervising intelligent systems and responding to genuine outliers.
              </p>
            </div>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6 tracking-tight border-b pb-4">The Genuine Challenges of AIoT Deployment</h2>
            <p className="text-lg text-slate-700 leading-relaxed mb-8">
              AIoT is not a category that tolerates superficial implementation. The challenges are real, and organisations that underestimate them will produce systems that underdeliver and erode confidence in the technology itself.
            </p>

            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="font-bold text-slate-900 text-lg mb-2 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm">1</span>
                  Data Security and Privacy
                </h3>
                <p className="text-slate-700 leading-relaxed">
                  AIoT systems process sensitive data at scale — behavioural patterns in homes, operational data in facilities, personal information inferred from usage. The security and privacy obligations are significant. Data in transit must be encrypted. Data at rest must be protected. Access must be controlled and auditable. Privacy-by-design is not optional — it is a legal and ethical requirement that must be embedded in system architecture from the outset.
                </p>
              </div>
              
              <div>
                <h3 className="font-bold text-slate-900 text-lg mb-2 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm">2</span>
                  Data Quality and Integrity
                </h3>
                <p className="text-slate-700 leading-relaxed">
                  AI models are only as reliable as the data they learn from. Sensor failures, calibration drift, network interruptions, and inconsistent data schemas produce training data that degrades model performance in ways that are often difficult to detect until operational consequences materialise. Data quality management — validation, cleaning, anomaly detection at the data layer — is a foundational requirement, not an afterthought.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-slate-900 text-lg mb-2 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm">3</span>
                  Integration Complexity
                </h3>
                <p className="text-slate-700 leading-relaxed">
                  Real environments contain equipment and systems from multiple vendors, generations, and communication protocols. Achieving meaningful integration across this heterogeneous landscape — rather than producing another isolated data silo with an AI layer on top — requires significant architectural effort. Middleware, protocol translation, unified data models, and API governance are all part of the solution, but none of them are simple.
                </p>
              </div>

              <div>
                <h3 className="font-bold text-slate-900 text-lg mb-2 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm">4</span>
                  Investment and Infrastructure Requirements
                </h3>
                <p className="text-slate-700 leading-relaxed">
                  Deploying AIoT at a scale where AI models produce reliable, actionable intelligence requires adequate data infrastructure: sufficient sensor density, reliable connectivity, appropriate edge and cloud computing capacity, and a data platform capable of handling the volume and variety of signals generated. The investment required is genuine, and the ROI case must be built explicitly and tracked rigorously.
                </p>
              </div>

              <div className="md:col-span-2">
                <h3 className="font-bold text-slate-900 text-lg mb-2 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm">5</span>
                  Capability and Talent
                </h3>
                <p className="text-slate-700 leading-relaxed">
                  Operating an AIoT environment requires capabilities that span IoT engineering, data science, cybersecurity, and operational domain expertise. Few organisations have this combination in-house, and the market for individuals who do is competitive. This makes the choice of implementation and managed services partner a critical strategic decision, not simply a procurement exercise.
                </p>
              </div>
            </div>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6 tracking-tight border-b pb-4">Engineering Intelligence Into Connected Environments</h2>
            
            <div className="space-y-6">
              <div className="border-l-4 border-blue-500 pl-6 py-2">
                <h3 className="font-bold text-slate-800 text-lg mb-2">Unified Data Architecture as the Foundation</h3>
                <p className="text-slate-700 leading-relaxed">
                  The prerequisite for operational AI is a coherent data foundation: a unified platform that aggregates sensor data across devices, systems, and locations into a consistent, queryable schema. Without this, AI models train on inconsistent inputs and produce unreliable outputs. The data architecture decision — edge processing versus cloud centralisation, streaming versus batch, open versus proprietary schema — shapes everything downstream and must be made deliberately.
                </p>
              </div>

              <div className="border-l-4 border-blue-500 pl-6 py-2">
                <h3 className="font-bold text-slate-800 text-lg mb-2">AI Models Calibrated to Operational Context</h3>
                <p className="text-slate-700 leading-relaxed">
                  Generic AI models applied to specific operational environments produce generic results. The most effective AIoT deployments train models on data from the specific assets, buildings, and processes they will operate in — capturing the particular patterns, failure modes, and usage behaviours of that environment. This requires time and data volume to achieve, which is why phased deployment with continuous model improvement consistently outperforms big-bang implementations.
                </p>
              </div>

              <div className="border-l-4 border-blue-500 pl-6 py-2">
                <h3 className="font-bold text-slate-800 text-lg mb-2">Security Architecture Designed for Connected Operational Environments</h3>
                <p className="text-slate-700 leading-relaxed">
                  AIoT security requires a layered approach that addresses the full stack: device-level security (hardened firmware, unique credentials, secure boot), network security (segmentation, encrypted communication, intrusion detection), platform security (role-based access, audit logging, vulnerability management), and data security (encryption at rest and in transit, privacy controls, retention policies). Each layer is a necessary condition, not a sufficient one.
                </p>
              </div>

              <div className="border-l-4 border-blue-500 pl-6 py-2">
                <h3 className="font-bold text-slate-800 text-lg mb-2">Human-Centred Design for Operational Interfaces</h3>
                <p className="text-slate-700 leading-relaxed">
                  The intelligence of an AIoT system is only as useful as the ability of the people operating it to act on its outputs. Operational interfaces must present synthesised, prioritised intelligence — not raw data — in formats that support fast, confident decision-making. Alert design, dashboard information architecture, and escalation workflows are as important to operational outcomes as the quality of the underlying models.
                </p>
              </div>
            </div>
            
            <p className="text-lg text-slate-700 leading-relaxed mt-8 bg-blue-50 rounded-2xl p-6 italic shadow-inner">
              IoTrenetics approaches AIoT deployment as an integrated engineering challenge, not a technology installation. The work begins with understanding the specific operational environment, data landscape, and performance objectives of each client — residential, commercial, or industrial. From that foundation, IoTrenetics designs unified data architectures, selects and deploys appropriate sensing infrastructure, develops and trains AI models calibrated to the specific context, and builds the security and integration layers that allow intelligent systems to operate reliably at scale. The outcome is not a connected building or a monitored facility. It is an environment with genuine operational intelligence — one that learns, adapts, and delivers measurable value over time.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6 tracking-tight border-b pb-4">From Connected to Intelligent: The Defining Transition</h2>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              The distinction between IoT and AIoT is not a marketing distinction. It is an operational one. A connected system collects data. An intelligent system uses it. The gap between those two states is where most organisations currently sit — with significant connectivity investments that are not yet delivering the analytical and predictive value they were intended to produce.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              Closing that gap requires more than adding an AI layer to an existing deployment. It requires rethinking the data architecture, the security posture, the integration approach, and the operational workflows that the system supports. Done correctly, the result is an environment that does not simply automate known tasks — it identifies unknown opportunities, surfaces unexpected risks, and improves continuously as it accumulates operational experience.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-6">
              For homeowners, this means living environments that genuinely anticipate needs rather than following scripts. For commercial and industrial operators, it means facilities and processes that run at an efficiency level that human management alone cannot achieve — and a competitive advantage that compounds over time as the intelligence embedded in operations becomes deeper and more accurate.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed font-semibold">
              The environments of the next decade will not be defined by how many devices they contain. They will be defined by how intelligently those devices work together. Organisations that build that intelligence now — with the right architecture, the right data strategy, and the right implementation partner — will find that the distance between where they are and where their industry is heading is shorter than they expected.
            </p>
          </section>

          {/* Footer Card */}
          <div className="bg-slate-900 rounded-3xl p-8 md:p-12 text-center text-white shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 -mr-8 -mt-8 w-32 h-32 rounded-full bg-blue-500 opacity-20 blur-2xl"></div>
            <div className="absolute bottom-0 left-0 -ml-8 -mb-8 w-32 h-32 rounded-full bg-teal-500 opacity-20 blur-2xl"></div>
            
            <h3 className="text-2xl font-bold mb-4 tracking-tight">IoTrenetics<span className="font-light opacity-80 mx-3">|</span>Intelligence in Motion</h3>
            <p className="text-slate-300 text-lg mb-8 max-w-2xl mx-auto leading-relaxed">
              IoTrenetics designs and deploys AIoT environments — integrating connected sensing, AI-driven analytics, unified data platforms, and security-first architecture into intelligent systems that learn, adapt, and deliver sustained operational value across residential, commercial, and industrial environments.
            </p>
            <a href="https://www.iotrenetics.com" target="_blank" rel="noreferrer" className="inline-block bg-blue-600 hover:bg-blue-500 text-white font-medium px-8 py-3 rounded-full transition-colors duration-300 shadow-lg shadow-blue-500/30">
              www.iotrenetics.com
            </a>
          </div>

        </article>
      </div>
    </div>
  );
};

export default AIOT;
